---

- hosts: all
  become: yes
  gather_facts: yes

  roles:
    - geerlingguy.nfs
    - geerlingguy.packer-debian

  tasks:
  - import_role:
       name: ethereum
  - apt: "name={{ item }} state=installed"
    with_items:
      - wget
      - curl
      - vim