---

- hosts: all
  become: yes
  gather_facts: yes

  tasks:
  - name: Execute nfs role
    include_role:
      name: geerlingguy.nfs

  - name: Execute packer role
    include_role:
      name: geerlingguy.packer-debian

  - name: Execute Ethereum server role
    include_role:
      name: ethereum_server

